#!/bin/bash

mkdir -p assets





BASEDIR="gs://genomics-public-data/resources/broad/hg38/v0/"




gsutil cp ${BASEDIR}/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz* assets/

gsutil cp ${BASEDIR}/Homo_sapiens_assembly38.dbsnp138.vcf* assets/

`


